"""Expand theories that are under 200 words to meet the minimum requirement."""

EXTRA = {
    "en_l1_u1_l3": (
        "\n\nFurthermore, understanding these expressions is essential "
        "for drafting legal documents. For instance, the word 'shall' "
        "is used in legislation to impose a mandatory obligation, whereas "
        "'may' confers a discretion upon the decision-maker. In practice, "
        "the distinction between 'shall' and 'may' can have significant "
        "legal consequences. A statute that says a public authority "
        "'shall' grant a permit creates a duty to do so, while one that "
        "says it 'may' grant a permit gives the authority a choice. "
        "Legal professionals must also understand the difference between "
        "'must' and 'should', where 'must' indicates a binding "
        "requirement and 'should' indicates a recommendation that is "
        "not legally enforceable. The expressions 'in accordance with' "
        "and 'subject to' are frequently encountered in commercial "
        "contracts and statutory provisions. These fixed expressions "
        "form the backbone of legal communication and must be mastered "
        "by anyone seeking to work in an English-speaking legal "
        "environment."
    ),
    "en_l1_u1_l5": (
        "\n\nThe UK constitution also includes the devolution settlements, "
        "which grant legislative and executive powers to the Scottish "
        "Parliament, the Welsh Senedd, and the Northern Ireland Assembly. "
        "These devolved institutions can legislate on matters within their "
        "competence, but the UK Parliament retains the sovereignty to "
        "legislate on any matter. The relationship between Westminster "
        "and the devolved institutions is governed by conventions and "
        "statute. Judicial review of government action is a vital "
        "mechanism for ensuring that the rule of law is maintained and "
        "that public bodies act within their legal powers."
    ),
    "en_l1_u1_l6": (
        "\n\nCivil cases in England and Wales are governed by the Civil "
        "Procedure Rules, which were introduced to streamline the "
        "litigation process and reduce costs. Pre-action protocols "
        "encourage parties to resolve disputes before proceedings "
        "are issued. The court has wide case management powers to "
        "ensure that cases progress efficiently. Proportionate case "
        "management means that the court will tailor its approach to "
        "the value and complexity of the dispute. Costs management "
        "orders require parties to provide estimated costs budgets "
        "at an early stage. These reforms have made civil litigation "
        "more accessible and efficient."
    ),
    "en_l1_u1_l7": (
        "\n\nThe criminal justice process in England and Wales follows "
        "a structured sequence. After an arrest, the suspect is "
        "interviewed by the police. The Crown Prosecution Service "
        "then decides whether to charge the suspect based on the "
        "realistic prospect of conviction test. If charged, the "
        "case proceeds to a preliminary hearing before the Magistrates' "
        "Court or the Crown Court. The defendant has the right to "
        "a fair trial, including the right to legal representation, "
        "the right to silence, and the presumption of innocence. "
        "Sentencing follows established guidelines published by the "
        "Sentencing Council. Appeals against conviction or sentence "
        "can be made to the Court of Appeal Criminal Division."
    ),
    "en_l1_u1_l8": (
        "\n\nThe CPR introduced a culture shift in civil litigation, "
        "moving away from the adversarial approach towards a more "
        "cooperative process. Parties are required to help the court "
        "further the overriding objective. This includes dealing with "
        "cases proportionately and ensuring that the parties are on "
        "an equal footing. The court can impose adverse costs orders "
        "against parties who fail to comply with rules, directions, "
        "or court orders. Part 36 offers are a powerful tactical "
        "tool that encourage early settlement by imposing costs "
        "consequences on parties who fail to accept reasonable offers."
    ),
    "en_l1_u1_l9": (
        "\n\nEmployment tribunal claims must generally be brought "
        "within three months of the effective date of termination. "
        "The tribunal has the power to extend this time limit in "
        "certain exceptional circumstances. Remedies available in "
        "the employment tribunal include reinstatement, re-engagement, "
        "and compensation. The basic award is calculated in a similar "
        "way to a statutory redundancy payment. The compensatory award "
        "is designed to compensate the employee for actual financial "
        "loss resulting from the dismissal. The tribunal can also make "
        "a recommendation that the employer take specified steps to "
        "reduce the adverse effect of the discrimination on the "
        "claimant."
    ),
    "en_l1_u1_l10": (
        "\n\nFinancial remedies in family proceedings are governed by "
        "the Matrimonial Causes Act 1973. The court considers a range "
        "of factors including the income, earning capacity, property, "
        "and financial needs of each party. The starting point is "
        "equal sharing of the matrimonial assets, subject to any "
        "statutory departure factors. In children cases, the welfare "
        "checklist in section 1(3) of the Children Act 1989 guides "
        "the court's decision-making. The no order principle means "
        "that the court will not make an order unless it considers "
        "that doing so would be better for the child than making no "
        "order."
    ),
    "en_l2_u1_l3": (
        "\n\nThe doctrine of privity means that only parties to a "
        "contract can enforce its terms. This means that a third "
        "party cannot sue on a contract to which they are not a "
        "party, even if the contract was made for their benefit. "
        "However, the Contracts (Rights of Third Parties) Act 1999 "
        "reformed this doctrine by allowing third parties to enforce "
        "terms that expressly confer a benefit on them. Duress and "
        "undue influence are vitiating factors that can render a "
        "contract voidable. Misrepresentation, whether fraudulent, "
        "negligent, or innocent, provides the innocent party with "
        "a remedy in damages or rescission. The implied terms "
        "incorporated by statute, such as the Sale of Goods Act "
        "terms as to quality and fitness, provide additional "
        "protection for contracting parties."
    ),
    "en_l2_u1_l4": (
        "\n\nVicarious liability is an important aspect of tort law "
        "whereby an employer is held liable for the torts of its "
        "employees committed in the course of employment. This is "
        "a strict liability doctrine based on the policy that the "
        "employer who profits from the employee's activities should "
        "bear the risk of negligent conduct. The key test is whether "
        "there is a sufficient connection between the employment and "
        "the wrongful act. Product liability under the Consumer "
        "Protection Act 1987 makes manufacturers strictly liable "
        "for damage caused by defective products. Defamation law "
        "protects reputation through the torts of libel (permanent "
        "form) and slander (temporary form)."
    ),
    "en_l2_u1_l5": (
        "\n\nThe Sale of Goods Act 1979 implies that goods sold must "
        "conform to any description and match any sample shown to "
        "the buyer. The buyer has the right to reject goods that do "
        "not conform and to claim damages for any loss suffered. "
        "The Consumer Rights Act 2015 strengthened consumer protection "
        "by providing a thirty-day right to reject faulty goods and "
        "a right to a repair or replacement. In agency law, the "
        "agent's authority can be actual (expressly or impliedly "
        "granted by the principal) or apparent (created by the "
        "principal's representations to a third party). The "
        "distinction between a partnership and a limited company is "
        "significant for liability purposes, as partners have "
        "unlimited personal liability while shareholders of limited "
        "companies enjoy limited liability."
    ),
    "en_l2_u1_l6": (
        "\n\nThe grounds of judicial review have been developed "
        "through case law, most notably in the GCHQ case (1985) "
        "and Council of Civil Service Unions v Minister for the "
        "Civil Service (1985). Proportionality has become an "
        "increasingly important ground, particularly in human "
        "rights cases. The court will assess whether the decision "
        "was a proportionate means of achieving a legitimate aim. "
        "The Equality Act 2010 also provides grounds for challenge "
        "where public bodies act in a discriminatory manner. "
        "Standing to apply for judicial review has been liberalised "
        "and any person with a sufficient interest may apply."
    ),
    "en_l2_u1_l7": (
        "\n\nBeneficial interests under a trust arise where the "
        "legal title to property is held by trustees for the "
        "benefit of beneficiaries. A resulting trust arises where "
        "the beneficial interest returns to the settlor. A "
        "constructive trust is imposed by the court to prevent "
        "unjust enrichment. The Landlord and Tenant Act 1954 "
        "gives business tenants a statutory right to renew their "
        "lease. The Land Compensation Act 1973 provides for "
        "compensation when land is compulsorily acquired by the "
        "state. The planning system controls the development and "
        "use of land through the grant of planning permission by "
        "local planning authorities."
    ),
    "en_l2_u1_l8": (
        "\n\nService of court documents abroad is governed by "
        "international conventions such as the Hague Service "
        "Convention. The recognition of foreign court judgments "
        "at common law requires the judgment to be final, for "
        "a definite sum, and rendered by a court of competent "
        "jurisdiction. The Enforcement of Foreign Judgments "
        "Act 1933 provides a statutory framework for the "
        "registration of judgments from countries that have "
        "reciprocal enforcement arrangements with the UK. "
        "Anti-suit injunctions may be granted to prevent a "
        "party from commencing or continuing proceedings in a "
        "foreign court where there is an adequate alternative "
        "forum available."
    ),
    "en_l2_u1_l9": (
        "\n\nThe court has discretion in awarding damages and may "
        "take into account the conduct of the parties, including "
        "whether the claimant has failed to mitigate their loss. "
        "The measure of damages depends on the type of claim. In "
        "contract, damages are designed to put the innocent party "
        "in the position they would have been in had the contract "
        "been performed. In tort, damages are designed to put the "
        "claimant in the position they would have been in had the "
        "tort not been committed. Interest on damages may be "
        "awarded under the Supreme Court Act 1981 from the date "
        "of loss to the date of judgment."
    ),
    "en_l2_u1_l10": (
        "\n\nThe rules on admissibility of evidence are designed to "
        "ensure that only reliable and relevant evidence is placed "
        "before the court. The bad character provisions of the "
        "Criminal Justice Act 2003 allow evidence of a defendant's "
        "previous convictions to be admitted in certain circumstances. "
        "The hearsay provisions in the Criminal Justice Act 2003 "
        "and the Civil Evidence Act 1995 have liberalised the "
        "rules on hearsay evidence. Expert evidence is governed "
        "by Part 35 of the CPR and requires the court's permission. "
        "The expert owes a duty to the court that overrides any "
        "duty to the party instructing them."
    ),
    "en_l3_u1_l1": (
        "\n\nThe interpretation of legislation is guided by the "
        "presumption that Parliament does not intend to override "
        "fundamental rights. Where legislation is capable of two "
        "meanings, the court will prefer the interpretation that "
        "is compatible with Convention rights under the Human "
        "Rights Act 1998. EU-derived legislation that remained "
        "in UK law after Brexit continues to be interpreted in "
        "accordance with the principles of EU law where consistent "
        "with the text. The court will also have regard to "
        "explanatory notes published by the government alongside "
        "the Act, although these are not legally binding."
    ),
    "en_l3_u1_l2": (
        "\n\nThe European Court of Human Rights has adopted a "
        "purposive approach to the interpretation of the "
        "Convention. The domestic courts increasingly follow this "
        "approach, particularly when interpreting the Human Rights "
        "Act 1998. The Supreme Court in R (on the application of "
        "SK) v Secretary of State for Work and Pensions [2015] "
        "endorsed a holistic, Article 14-compliant approach to "
        "statutory interpretation. Reference materials such as "
        "Hansard (parliamentary debates) may be considered by "
        "the court when determining the background to the "
        "legislation, following Pepper v Hart [1993]."
    ),
    "en_l3_u1_l3": (
        "\n\nModern legal drafting favours plain English over "
        "traditional legal jargon. The Law Commission has "
        "recommended the use of plain language in legislation. "
        "Drafters should avoid unnecessary complexity, use active "
        "voice where possible, and structure documents logically. "
        "The use of defined terms improves clarity and reduces "
        "the risk of ambiguity. Schedules and annexes can be used "
        "to supplement the main body of the document without "
        "cluttering it with detail. Each clause should deal with "
        "a single topic and be expressed as clearly and concisely "
        "as possible."
    ),
    "en_l3_u1_l4": (
        "\n\nAfter completion, the buyer becomes the legal owner "
        "of the property and assumes responsibility for all "
        "outgoings including council tax, utility bills, and "
        "ground rent where applicable. The seller's solicitor "
        "must ensure that all encumbrances on the title are "
        "discharged prior to or at completion. Leasehold "
        "conveyancing involves additional considerations such "
        "as the terms of the lease, service charges, and the "
        "need for consent from the freeholder or management "
        "company. The electronic communications network and "
        "sewerage agreements may affect the property and "
        "should be investigated during the conveyancing process."
    ),
    "en_l3_u1_l5": (
        "\n\nEffective legal research requires an understanding "
        "of the hierarchy of sources and the weight to be given "
        "to each. Primary legislation is the highest authority, "
        "followed by secondary legislation and then case law. "
        "Academic commentary and textbooks are persuasive rather "
        "than binding. The researcher must evaluate the currency "
        "and relevance of each source. Research should be "
        "systematic and well-documented, with clear records of "
        "the sources consulted and the conclusions reached. "
        "Time management is essential in legal research, as "
        "deadlines must be met and resources allocated efficiently."
    ),
    "en_l3_u1_l6": (
        "\n\nThe courts have indicated that unreasonable refusal "
        "to engage in ADR may result in costs sanctions. In "
        "Halsey v Milton Keynes General NHS Trust [2011], the "
        "Court of Appeal held that while courts cannot compel "
        "parties to mediate, unreasonable refusal to do so may "
        "be taken into account when awarding costs. Mediation "
        "agreements are enforceable as contracts. Arbitration "
        "agreements must comply with the requirements of section "
        "5 of the Arbitration Act 1996. The court has limited "
        "supervisory jurisdiction over arbitration proceedings, "
        "including the power to remove an arbitrator for serious "
        "irregularity and to challenge an award on a point of law."
    ),
    "en_l3_u1_l7": (
        "\n\nThe ECHR rights are qualified, meaning they can be "
        "limited where such limitation is prescribed by law, "
        "necessary in a democratic society, and proportionate "
        "to the legitimate aim pursued. The courts apply a "
        "balancing exercise under Article 10(2) when assessing "
        "whether a restriction on freedom of expression is "
        "justified. The Equality Act 2010, while not part of "
        "the ECHR framework, works alongside it to provide "
        "comprehensive protection against discrimination. The "
        "UK's membership of the Council of Europe created "
        "obligations under the ECHR, and the Human Rights Act "
        "1998 gave domestic effect to these obligations."
    ),
    "en_l3_u1_l8": (
        "\n\nThe Companies Act 2006 introduced a statutory code "
        "of directors' duties in sections 171 to 177, which "
        "codified the common law and equitable duties. Directors "
        "must declare any interest in a proposed transaction. "
        "Related party transactions must be approved by the "
        "shareholders. The court may grant relief to a director "
        "who has acted honestly and reasonably under section 1157 "
        "of the Act. Insolvency law intersects with company law "
        "when a company is unable to pay its debts, triggering "
        "potentially wrongful or fraudulent trading provisions."
    ),
    "en_l3_u1_l9": (
        "\n\nThe duration of copyright varies depending on the "
        "type of work. For literary, dramatic, musical, and "
        "artistic works, copyright lasts for the life of the "
        "author plus seventy years. For sound recordings and "
        "films, it lasts for seventy years from the date of "
        "publication. For broadcasts, it lasts for fifty years. "
        "Moral rights, which include the right of paternity and "
        "the right of integrity, protect the personal interests "
        "of the author. These rights cannot be assigned but can "
        "be waived. The Digital Economy Act 2010 addresses "
        "copyright infringement in the digital environment."
    ),
    "en_l3_u1_l10": (
        "\n\nThe Environment Act 2021 introduced new duties on "
        "public authorities to have regard to biodiversity "
        "enhancement. Biodiversity gain is now required for "
        "most development projects in England. Water resources "
        "management is regulated through abstraction licences "
        "and water company obligations. Environmental standards "
        "are enforced through environmental permits and "
        "prosecutions for breach. The concept of the "
        "precautionary principle plays an important role in "
        "environmental regulation, requiring preventive action "
        "even where scientific certainty is lacking."
    ),
    "en_l4_u1_l1": (
        "\n\nEffective advocacy requires mastery of both "
        "the substantive law and the procedural rules governing "
        "the case. Counsel must be able to identify and distil "
        "the key issues from a mass of evidence and present them "
        "concisely. The ability to respond to judicial questions "
        "with composure and accuracy is critical. Cross-examination "
        "of witnesses requires skill in eliciting evidence that "
        "supports the client's case while exposing weaknesses "
        "in the opposing case. The Advocate's duty is to the "
        "court, and this duty overrides any duty to the client."
    ),
    "en_l4_u1_l2": (
        "\n\nThe success of a negotiation often depends on thorough "
        "preparation and the ability to read the other party's "
        "position. Understanding cultural differences is important "
        "in international negotiations. The use of frameworks such "
        "as the Harvard Negotiation Project's principled negotiation "
        "method can help structure the process. Maintaining a "
        "professional relationship while protecting the client's "
        "interests requires diplomacy and strategic thinking. "
        "Written follow-up to confirm the terms agreed is essential "
        "to avoid subsequent disputes about the negotiation outcome."
    ),
    "en_l4_u1_l3": (
        "\n\nThe Financial Services and Markets Act 2000 also "
        "established the Financial Services Compensation Scheme, "
        "which provides protection for customers of failed "
        "financial firms. The Payment Services Regulations 2017 "
        "govern the regulation of payment service providers. "
        "Consumer credit is regulated under the Consumer Credit "
        "Act 1974. The regulation of financial products and "
        "services continues to evolve in response to new "
        "technologies and market developments, including "
        "fintech, cryptocurrencies, and digital banking."
    ),
    "en_l4_u1_l4": (
        "\n\nThe General Anti-Abuse Rule (GAAR) was introduced "
        "in 2013 to counter aggressive tax avoidance schemes. "
        "HMRC has the power to issue accelerated payment notices "
        "requiring payment of disputed tax before the outcome "
        "of an appeal is determined. Transfer pricing rules "
        "ensure that transactions between connected persons "
        "reflect arm's length values. Tax residency is "
        "determined by the Statutory Residence Test. Double "
        "taxation treaties prevent the same income from being "
        "taxed in more than one jurisdiction."
    ),
    "en_l4_u1_l5": (
        "\n\nThe Immigration Act 2014 and 2016 introduced "
        "measures to deter illegal working and overstaying. "
        "Employers have a duty to check the immigration status "
        "of workers and face civil penalties for employing "
        "those without the right to work. Sponsorship of "
        "skilled workers is governed by the points-based system, "
        "which assigns points based on salary, skills, and "
        "qualifications. Family reunion provisions allow certain "
        "family members of refugees to join them in the UK. "
        "Judicial review of immigration decisions is subject "
        "to specific procedural requirements."
    ),
    "en_l4_u1_l6": (
        "\n\nThe Care Quality Commission regulates health and "
        "social care services in England. The Mental Health "
        "Act 1983 provides the framework for compulsory "
        "detention and treatment of persons with mental "
        "disorders. The Mental Capacity Act 2005 protects "
        "persons who lack capacity to make their own decisions. "
        "Advance decisions (living wills) allow individuals "
        "to refuse treatment in advance. The Human Fertilisation "
        "and Embryology Act regulates fertility treatment and "
        "embryo research. Coroners investigate deaths that are "
        "unnatural, violent, or of unknown cause."
    ),
    "en_l4_u1_l7": (
        "\n\nThe Information Commissioner's Office (ICO) is "
        "independent authority responsible for enforcing data "
        "protection law in the UK. Fines for data protection "
        "breaches can be up to 17.5 million pounds or four "
        "percent of annual global turnover. Privacy by design "
        "requires organisations to consider data protection "
        "from the outset of any project. Data protection impact "
        "assessments are required for high-risk processing "
        "activities. The Privacy and Electronic Communications "
        "Regulations 2003 govern electronic marketing and "
        "the use of cookies."
    ),
    "en_l4_u1_l8": (
        "\n\nThe tribunal in an international arbitration has "
        "the power to order interim measures, including the "
        "appointment of an emergency arbitrator before the "
        "tribunal is constituted. challenges to an arbitral "
        "award are limited to the grounds set out in section "
        "67 (lack of substantive jurisdiction) and section 68 "
        "(serious irregularity) of the Arbitration Act 1996. "
        "The court's power to intervene is deliberately "
        "circumscribed to preserve the finality of arbitration. "
        "Investor-state arbitration under bilateral investment "
        "treaties is a growing area of international arbitration."
    ),
    "en_l4_u1_l9": (
        "\n\nTreaties can be bilateral (between two states) or "
        "multilateral (between three or more states). The process "
        "of treaty-making involves negotiation, authentication, "
        "signature, ratification, and entry into force. A state "
        "may express its consent to be bound by a treaty through "
        "ratification, acceptance, approval, or accession. "
        "Reservations are unilateral statements made by a state "
        "when signing or ratifying a treaty, modifying the legal "
        "effects of certain provisions. The International Court "
        "of Justice provides judicial settlement of disputes "
        "between states arising from treaties."
    ),
    "en_l4_u1_l10": (
        "\n\nThe European Convention on Human Rights has influenced "
        "legal systems across Europe, requiring them to incorporate "
        "fundamental rights protections. International trade law "
        "is governed by the World Trade Organization (WTO) "
        "framework, which sets rules for international commerce. "
        "The principle of comity requires courts of different "
        "jurisdictions to respect each other's laws and "
        "decisions. Transnational litigation raises complex "
        "issues of jurisdiction, applicable law, and enforcement "
        "of judgments. The development of international "
        "commercial law has been influenced by the work of "
        "UNCITRAL in producing model laws and conventions."
    ),
}


def expand(lessons):
    """Expand theories under 200 words by appending extra content."""
    for lesson in lessons:
        lid = lesson["id"]
        tlen = len(lesson["theory"].split())
        if tlen < 200 and lid in EXTRA:
            lesson["theory"] = lesson["theory"] + EXTRA[lid]
        # Verify
        final_tlen = len(lesson["theory"].split())
        vcount = len(lesson["vocab"])
        status = "OK" if vcount >= 10 and final_tlen >= 200 else "FAIL"
        print(f"  {lid}: vocab={vcount}, theory_en={final_tlen}w [{status}]")
    return lessons
